*&---------------------------------------------------------------------*
*& Report ZFI45
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZFI45.
TABLES:ZFI45.
DATA ZBUKR TYPE ZFI45-ZBUKR.
DATA LIFNR TYPE ZFI45-LIFNR.

PARAMETERS     : P_ZBUKR TYPE WERKS DEFAULT 1000.
SELECT-OPTIONS : P_LIFNR FOR LIFNR.
DATA :
T_SPFLI  LIKE TABLE OF ZFI45,
ALV           TYPE REF TO CL_SALV_TABLE,
ERROR_MESSAGE TYPE REF TO CX_SALV_MSG.
SELECT * INTO CORRESPONDING FIELDS OF TABLE
@T_SPFLI FROM ZFI45
WHERE ZBUKR = @P_ZBUKR AND LIFNR IN @P_LIFNR
ORDER BY ZALDT.
TRY.
    CL_SALV_TABLE=>FACTORY(
      IMPORTING
        R_SALV_TABLE = ALV
      CHANGING
        T_TABLE      = T_SPFLI ).
  CATCH CX_SALV_MSG INTO ERROR_MESSAGE.    " ERROR HANDLING
ENDTRY.
ALV->GET_FUNCTIONS( )->SET_ALL( ).
ALV->GET_COLUMNS( )->GET_COLUMN( 'MANDT' )->SET_VISIBLE( IF_SALV_C_BOOL_SAP=>FALSE ).
DATA COLUMN TYPE REF TO CL_SALV_COLUMN.

*COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'ORD_CREATED_BY' ).
*COLUMN->SET_LONG_TEXT( 'ORD_CREATED_BY' ).
*COLUMN->SET_OUTPUT_LENGTH( 15 ).

ALV->GET_DISPLAY_SETTINGS( )->SET_LIST_HEADER( |مشاهده اطلاعات چکها   { LINES( T_SPFLI ) }  رکورد |  ).
ALV->DISPLAY( ).
