"Name: \PR:SAPLFIPI\FO:XFTPOST_ANALYSIEREN\SE:END\EI
ENHANCEMENT 0 ZLFIPIF00.
*
IF XFTPOST-FNAM = 'RF05A-PORTF'.
  BREAK OMRANI.
  DELETE FTA WHERE FNAM = 'RF05A-PORTF'.
  MOVE-CORRESPONDING XFTPOST TO FTF.
  APPEND FTF.
ENDIF.

ENDENHANCEMENT.
