PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_300.
  MODULE FUNKTIONSTASTEN_450.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PCEC-HBKID.
    FIELD PCEC-HKTID.
    MODULE BANK2_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    FIELD PAYR-CHECF.
    FIELD PCEC-HBKID.
    FIELD PCEC-HKTID.
    FIELD PCEC-CHECF.
    MODULE SCHECK_ZUORD_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.
