PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_200.
  MODULE FUNKTIONSTASTEN_200.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-GJAHR.
    FIELD PAYR-VBLNR.
    MODULE AUSWAHL_BEARBEITEN.
    MODULE BELEG_GJAHR_PRUEFEN.
    MODULE INFOS_AUSGEBEN.
  ENDCHAIN.
