PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_300.
  MODULE FUNKTIONSTASTEN_400.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  FIELD PCEC-CHECF MODULE WARNUNG_AUSGEBEN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-CHECF.
    FIELD PAYR-CHECT.
    FIELD PCEC-CHECF.
    MODULE SCHECK_UMNUM_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    FIELD PAYR-CHECF.
    FIELD PAYR-CHECT.
    MODULE BERECHTIGUNG_PAI.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-VOIDR.
    FIELD TVOIT-VOIDT.
    MODULE GRUND_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PCEC-CHECF.
    MODULE AUSWAHL_BEARBEITEN.
  ENDCHAIN.







