PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_100.
  MODULE FUNKTIONSTASTEN_800.
  MODULE SCREEN_MODIF_800.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  CHAIN.
    FIELD PAYR-CHECT.
    MODULE SCHECKNUMMER_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    FIELD T012-BANKL.
    FIELD T012K-BANKN.
    FIELD PAYR-CHECT.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
    MODULE BANK_NUMMERN_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-CHECT.
    MODULE SCHECK_AENDR_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-VOIDR.
    MODULE GRUND_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD UF05A-STGRD.
    FIELD T041CT-TXT40.
    MODULE STORNOGRUND_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    FIELD T012-BANKL.
    FIELD T012K-BANKN.
    FIELD PAYR-CHECT.
    FIELD PAYR-VOIDR.
    FIELD UF05A-STGRD.
    field rf05r-budat.
    field rf05r-monat.
    MODULE BERECHTIGUNG_PAI.
    MODULE SCHECK_RUECK_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.
