PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_750.
  MODULE FUNKTIONSTASTEN_750.
  MODULE MODIFY_SCREEN.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  MODULE OPAYF_RESET.
  CHAIN.
    FIELD OPAYF-BUKRS.
    FIELD BKPF-BELNR.
    FIELD BKPF-GJAHR.
    FIELD OPAYF-RZAWE.
    FIELD OPAYF-PSTAP.
    FIELD OPAYF-PZFOR.
    FIELD OPAYF-PPRIZ.
    FIELD OPAYF-PPRIA.
    FIELD OPAYF-PSOFO.
    FIELD OPAYF-PESPR.
    FIELD OPAYF-PISOC.
    FIELD OPAYF-PFILL.
    FIELD OPAYF-XPDRU.
    FIELD OPAYF-XNOVO.
    FIELD OPAYF-PDFFO.
    MODULE DRUCK_BUKREIS.
    MODULE DRUCK_PRUEFEN.
    MODULE DRUCK_VORBEREITEN.
    MODULE DRUCKVORGABEN_SAVE.
    MODULE AUSWAHL_BEARBEITEN.
  ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD OPAYF-PSTAP MODULE F4_STAPL_750.

PROCESS ON HELP-REQUEST.
  FIELD OPAYF-PDFFO MODULE F1_PDFFO.













