PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_300.
  MODULE FUNKTIONSTASTEN_300.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD RFPDO2-CHKNXPER.
    MODULE BERECHTIGUNG_PAI.
  ENDCHAIN.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-CHECF.
    FIELD PAYR-CHECT.
    MODULE SCHECK_FREI2_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-VOIDR.
    FIELD TVOIT-VOIDT.
    MODULE GRUND_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.











