PROCESS BEFORE OUTPUT.
  MODULE BERECHTIGUNG_PBO.
  MODULE FUNKTIONSTASTEN_601.
  MODULE SCREEN_MODIF_601.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  CHAIN.
    FIELD PAYR-BANCD.
    MODULE SCHECK_SICHR_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.
