PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_500.
  MODULE FUNKTIONSTASTEN_500.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  FIELD PAYR-ZBUKR MODULE BERECHTIGUNG_PAI.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-GJAHR.
    FIELD PAYR-VBLNR.
    MODULE BELEG_GJAHR_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-CHECT.
    MODULE SCHECK_FREI1_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-GJAHR.
    FIELD PAYR-VBLNR.
    MODULE BELEG_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.
