PROCESS BEFORE OUTPUT.
  MODULE FUNKTIONSTASTEN_651.
  MODULE SET_CURSOR_651.
  MODULE SET_SIZE_651.
  LOOP AT TAB_PAYR WITH CONTROL FCHR_CONTROL CURSOR HLP_LNMAX .
    MODULE SCHECKS_AUFLISTEN.
  ENDLOOP.
  MODULE SCHECK_SPERRE.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  LOOP at tab_payr.
    CHAIN.
      FIELD *PAYR-CHECT.
      FIELD *PAYR-RWBTR.
      FIELD BSEG-VALUT.
      FIELD *PAYR-BANCD.
      FIELD BSEG-DMBTR.
      MODULE SCHECK_RLAUF_PRUEFEN ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE GET_CURSOR_651.
  MODULE AUSWAHL_BEARBEITEN.
