PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_100.
  MODULE FUNKTIONSTASTEN_600.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  CHAIN.
    FIELD PAYR-CHECT.
    MODULE AUSWAHL_BEARBEITEN.
    MODULE SCHECKNUMMER_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    FIELD T012-BANKL.
    FIELD T012K-BANKN.
    FIELD PAYR-CHECT.
    MODULE AUSWAHL_BEARBEITEN.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
    MODULE BANK_NUMMERN_PRUEFEN.
  ENDCHAIN.
  CHAIN.
    FIELD PAYR-CHECT.
    MODULE AUSWAHL_BEARBEITEN.
    MODULE SCHECK_AENDR_PRUEFEN.
  ENDCHAIN.
