PROCESS BEFORE OUTPUT.
  MODULE GET_PARAMETER_100.
  MODULE FUNKTIONSTASTEN_650.
*
PROCESS AFTER INPUT.
  MODULE BEENDEN AT EXIT-COMMAND.
  FIELD PAYR-ZBUKR MODULE BUKREIS_PRUEFEN.
  FIELD PAYR-ZBUKR MODULE BERECHTIGUNG_PAI.
  CHAIN.
    FIELD PAYR-ZBUKR.
    FIELD PAYR-HBKID.
    FIELD PAYR-HKTID.
    MODULE BANK_EINGABE_PRUEFEN.
    MODULE BANK_ID_PRUEFEN.
  ENDCHAIN.
  MODULE AUSWAHL_BEARBEITEN.
  MODULE SCHECK_RLAUF_INIT.
