*&---------------------------------------------------------------------*
*& Report ZVOUCHER
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZVOUCHER2.
"TABLES:mara,mldoc.
DATA BUKRS TYPE ZVOUCHER-BUKRS.
DATA GJAHR TYPE ZVOUCHER-GJAHR.
DATA MONAT TYPE ZVOUCHER-MONAT.
DATA BUDAT TYPE ZVOUCHER-BUDAT.
DATA BELNR TYPE ZVOUCHER-BELNR.
DATA HKONT TYPE ZVOUCHER-HKONT.
DATA KUNNR TYPE ZVOUCHER-KUNNR.
DATA LIFNR TYPE ZVOUCHER-LIFNR.
DATA MATNR TYPE ZVOUCHER-MATNR.
DATA EBELN TYPE ZVOUCHER-EBELN.
DATA VBEL2 TYPE ZVOUCHER-VBEL2.
DATA AUGBL TYPE ZVOUCHER-AUGBL.
DATA AUFNR TYPE ZVOUCHER-AUFNR.
DATA KOSTL TYPE ZVOUCHER-KOSTL.
DATA UMSKZ TYPE ZVOUCHER-UMSKZ.
DATA BED_IRR TYPE BSEG-DMBTR. "ZVOUCHER-BED_IRR.
DATA BES_IRR TYPE BSEG-DMBTR. "ZVOUCHER-BES_IRR.

PARAMETERS     : P_BUKRS TYPE BUKRS DEFAULT 1000.
SELECT-OPTIONS : P_GJAHR FOR GJAHR.
SELECT-OPTIONS : P_MONAT FOR MONAT.
SELECT-OPTIONS : P_BUDAT FOR BUDAT.
SELECT-OPTIONS : P_BELNR FOR BELNR.
SELECT-OPTIONS : P_HKONT FOR HKONT.
SELECT-OPTIONS : P_KUNNR FOR KUNNR.
SELECT-OPTIONS : P_LIFNR FOR LIFNR.
SELECT-OPTIONS : P_MATNR FOR MATNR.
SELECT-OPTIONS : P_EBELN FOR EBELN.
SELECT-OPTIONS : P_VBEL2 FOR VBEL2.
SELECT-OPTIONS : P_AUGBL FOR AUGBL.
SELECT-OPTIONS : P_AUFNR FOR AUFNR.
SELECT-OPTIONS : P_KOSTL FOR KOSTL.
SELECT-OPTIONS : P_UMSKZ FOR UMSKZ.
SELECT-OPTIONS : P_BEDIR FOR BED_IRR.
SELECT-OPTIONS : P_BESIR FOR BES_IRR.


DATA : BEGIN OF REC_ORD OCCURS 0,
EBELN LIKE EKES-EBELN,
EBELP LIKE EKES-EBELP,
END OF REC_ORD,
T_SPFLI  LIKE TABLE OF ZVOUCHER,
ALV           TYPE REF TO CL_SALV_TABLE,
ERROR_MESSAGE TYPE REF TO CX_SALV_MSG.
SELECT * INTO CORRESPONDING FIELDS OF TABLE @T_SPFLI
FROM ZVOUCHER AS Z WHERE Z~BUKRS = @P_BUKRS
AND Z~BELNR IN @P_BELNR
AND Z~HKONT IN @P_HKONT
AND Z~KUNNR IN @P_KUNNR
AND Z~LIFNR IN @P_LIFNR
AND Z~MATNR IN @P_MATNR
AND Z~EBELN IN @P_EBELN
AND Z~VBEL2 IN @P_VBEL2
AND Z~AUGBL IN @P_AUGBL
AND Z~AUFNR IN @P_AUFNR
AND Z~KOSTL IN @P_KOSTL
AND Z~BUDAT IN @P_BUDAT
AND Z~GJAHR IN @P_GJAHR
AND Z~MONAT IN @P_MONAT
AND Z~UMSKZ IN @P_UMSKZ
AND Z~BED_IRR IN @P_BEDIR
AND Z~BES_IRR IN @P_BESIR.

TRY.
    CL_SALV_TABLE=>FACTORY(
      IMPORTING
        R_SALV_TABLE = ALV
      CHANGING
        T_TABLE      = T_SPFLI ).
  CATCH CX_SALV_MSG INTO ERROR_MESSAGE.    " ERROR HANDLING
ENDTRY.







ALV->GET_FUNCTIONS( )->SET_ALL( ).
ALV->GET_COLUMNS( )->GET_COLUMN( 'MANDT' )->SET_VISIBLE( IF_SALV_C_BOOL_SAP=>FALSE ).
DATA COLUMN TYPE REF TO CL_SALV_COLUMN.

COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BUKRS' ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BUZEI' ).
COLUMN->SET_OUTPUT_LENGTH( 6 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BELNR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'GJAHR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BLDAT' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BUDAT' ).
COLUMN->SET_OUTPUT_LENGTH( 8 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'HKONT' ).
COLUMN->SET_OUTPUT_LENGTH( 8 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'LIFNR' ).
COLUMN->SET_OUTPUT_LENGTH( 8 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'KUNNR' ).
COLUMN->SET_OUTPUT_LENGTH( 8 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'KOSTL' ).
COLUMN->SET_OUTPUT_LENGTH( 8 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'AUFNR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'MATNR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).

COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BED' ).
COLUMN->SET_LONG_TEXT( 'BED' ).
COLUMN->SET_MEDIUM_TEXT( 'BED' ).
COLUMN->SET_SHORT_TEXT( 'BED' ).
COLUMN->SET_OUTPUT_LENGTH( 12 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BES' ).
COLUMN->SET_LONG_TEXT( 'BES' ).
COLUMN->SET_MEDIUM_TEXT( 'BES' ).
COLUMN->SET_SHORT_TEXT( 'BES' ).
COLUMN->SET_OUTPUT_LENGTH( 12 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'WAERS' ).
COLUMN->SET_OUTPUT_LENGTH( 6 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BED_IRR' ).
COLUMN->SET_LONG_TEXT( 'BED_IRR' ).
COLUMN->SET_MEDIUM_TEXT( 'BED_IRR' ).
COLUMN->SET_SHORT_TEXT( 'BED_IRR' ).
COLUMN->SET_OUTPUT_LENGTH( 12 ).
COLUMN->SET_DECIMALS( '0' ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BES_IRR' ).
COLUMN->SET_LONG_TEXT( 'BES_IRR' ).
COLUMN->SET_MEDIUM_TEXT( 'BES_IRR' ).
COLUMN->SET_SHORT_TEXT( 'BES_IRR' ).
COLUMN->SET_OUTPUT_LENGTH( 12 ).
COLUMN->SET_DECIMALS( '0' ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'AUGBL' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'VBELN' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'VBEL2' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'EBELN' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'EBELP' ).
COLUMN->SET_OUTPUT_LENGTH( 5 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BSCHL' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'VALUT' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'MATNR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'SGTXT' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'WERKS' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'QTY' ).
COLUMN->SET_LONG_TEXT( 'QTY' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'MEINS' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'AWKEY' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'BLART' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'CPUTM' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'XBLNR' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'KOART' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'TCODE' ).
COLUMN->SET_OUTPUT_LENGTH( 6 ).
COLUMN = ALV->GET_COLUMNS( )->GET_COLUMN( 'KURSF' ).
COLUMN->SET_LONG_TEXT( 'Exchange rate' ).
COLUMN->SET_OUTPUT_LENGTH( 10 ).
ALV->GET_DISPLAY_SETTINGS( )->SET_LIST_HEADER( |مشاهده اسناد حسابداري   { LINES( T_SPFLI ) }  رکورد |  ).
ALV->DISPLAY( ).
